name: 'IaC - Build an Release'

on:
  push:
    branches: [main]
    paths: [infrastrucutre/**]

defaults:
  run:
    working-directory: infrastrucutre

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: install all dependency
          run: pip install -r requirements-dev.txt
        - name: run unittests
          run: pytest --cov=./ --cov-report=xml
        - name: update code-coverage
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
            working-directory: ./infrastrucutre/
            files: ./coverage.xml # optional
            flags: unittests # optional
            name: webapp # optional
            fail_ci_if_error: true # optional (default = false)
        - name: cdk deploy
          uses: youyo/aws-cdk-github-actions@v2
          with:
            cdk_subcommand: 'deploy'
            actions_comment: true
            cdk_args: '--require-approval never'
            working_dir: "infrastrucutre"
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_IAC }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_IAC }}
            AWS_DEFAULT_REGION: 'eu-central-1'
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}