name: Frontend:Quality Gate

on:
  pull_request:
    branches: [main]
    paths: [frontend/**]
  push:
    branches: [main]
    paths: [frontend/**]

defaults:
  run:
    working-directory: frontend
    
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - name: lint all files
        run: yarn lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Cache
        uses: ./.github/actions/node-cache-restore
        id: cache-node-modules
        with:
          node-version: 16.x
      - name: run unittests
        run: yarn test:ci
      - name: Save Coverage-Report
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: frontend/coverage

  update-coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Coverage-Report
        uses: actions/download-artifact@master
        with:
          name: coverage
          path: frontend/coverage
      - name: update code-coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          working-directory: ./frontend/
          directory: ./coverage # optional
          flags: unittests, frontend # optional
          name: webapp # optional
          fail_ci_if_error: true # optional (default = false)