name: 'Frontend - Build an Release'

on:
  push:
    branches: [main]
    paths: [frontend/**]

defaults:
  run:
    working-directory: frontend

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v
      - name: configure credentials
        uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_WEB_APP }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_WEB_APP }}
          aws-region: "eu-central-1"
      - name: retrieve ssm parameter
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "sandboxDomainUri"
          env_variable_name: "sandboxDomainUri"
      - name: retrieve ssm parameter
        uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "sandboxHostingBucketName"
          env_variable_name: "sandboxHostingBucketName"
      - name: initialize Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install all dependency
        run: yarn install
      - name: lint all files
        run: yarn lint
      - name: run test
        run: yarn test:ci
      - name: update code-coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          working-directory: ./frontend/
          directory: ./coverage # optional
          flags: unittests # optional
          name: webapp # optional
          fail_ci_if_error: true # optional (default = false)
      - name: build project
        run: yarn build
        env:
          REACT_APP_SANDBOX_DOMAIN_URI: ${{ env.SANDBOXDOMAINURI }}
      - name: upload app to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --cache-control max-age=3600
        env:
          AWS_S3_BUCKET: ${{ env.SANDBOXHOSTINGBUCKETNAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_CICD_WEB_APP }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_CICD_WEB_APP }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'frontend/build'